---

language: python
python: "2.7"
sudo: required
dist: trusty

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # http://urllib3.readthedocs.io/en/latest/user-guide.html#ssl-py2
  pip install urllib3[secure]

  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  - "ansible-playbook tests/test.yml -i tests/inventory --connection=local"
  - "ansible-playbook tests/test.yml -i tests/inventory --connection=local"
  - /usr/sbin/php-fpm --version
  - /usr/sbin/php-fpm -m

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
