---

- name: Install libmagickwand
  apt: name=libmagickwand-6-headers state=present update_cache=yes cache_valid_time=3600
  become: yes
  when: ansible_distribution == 'Debian'

- name: Install libmagickwand
  apt: name=libmagickwand5 state=present update_cache=yes cache_valid_time=3600
  become: yes
  when: ansible_distribution == 'Ubuntu'

- name: Fetch imagick .deb
  get_url: url=https://ftp.weheartwebsites.de/{{ ansible_distribution | lower }}/{{ ansible_distribution_release }}/php7.0-imagick_{{ php7_ext_imagick_version }}_amd64.deb dest=/tmp/php7.0-imagick_{{ php7_ext_imagick_version }}_amd64.deb

- name: Install imagick .deb
  apt: deb=/tmp/php7.0-imagick_{{ php7_ext_imagick_version }}_amd64.deb
  become: yes