---

- name: install libhiredis
  apt:
    name: libhiredis0.10
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: fetch iredis .deb
  get_url:
    url: https://ftp.weheartwebsites.de/{{ ansible_distribution | lower }}/{{ ansible_distribution_release }}/php7.0-iredis_{{ php7fpm_ext_iredis_version }}_amd64.deb
    dest: /tmp/php7.0-iredis_{{ php7fpm_ext_iredis_version }}_amd64.deb

- name: install iredis .deb
  apt:
    deb: /tmp/php7.0-iredis_{{ php7fpm_ext_iredis_version }}_amd64.deb
  become: yes
  notify: restart_php7_fpm
